import AltGDA.Prelude
import AltGDA.EuclideanMatrix
import AltGDA.Simplex.Basic
import AltGDA.Simplex.Projection
import AltGDA.Simplex.KKT
import AltGDA.Game.Basic
import AltGDA.Game.Gap
import AltGDA.Game.Witness
import AltGDA.Game.Separation
import AltGDA.Game.GoldmanTucker
import AltGDA.Game.TuckerAlternative
import AltGDA.Game.GoldmanTuckerExistence
import AltGDA.Analysis.Constants
import AltGDA.Analysis.SupportGeometry
import AltGDA.Dynamics.AltGDA
import AltGDA.Dynamics.Averages
import AltGDA.Dynamics.KKTData
import AltGDA.Analysis.Residual
import AltGDA.Analysis.Energy
import AltGDA.Analysis.ResidualBudget
import AltGDA.Analysis.ShiftedTelescope
import AltGDA.Analysis.GapTelescope
import AltGDA.Analysis.RateFromBudget
import AltGDA.Analysis.ConditionalRate
import AltGDA.Analysis.ReflectionX
import AltGDA.Analysis.ReflectionY
import AltGDA.Analysis.PointwiseAbsorption
import AltGDA.MainTheorem
import AltGDA.MatrixTheorem
